### ISSUE TITLE
Config file resets to default every time the game is restarted

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Lothrazar/AutoPlant#1]
Minecraft Version: 1.16.5

Forge Version: 36.0.21

Mod Version: 0.1.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): 
When changing something in the config file and attempting to test changes I made to it, I found that the changes were not applied after restarting the game to attempt to apply said changes.

When I looked at the config file I found that it had reset itself back to it's default state and after doing some testing I found that this happens every time I start up the game.  This happens regardless of what I change in the config or how many changes I've made to the config. 

The changes I make to the config file just get erased every time I start up the game and this makes it impossible to configure the mod or add extra plants to the config.

Log file link: https://pastebin.com/n4CXWhvY

**Comment by Lothrazar** [comment]
Fix on the way

**Comment by The-Bernician-Lamb** [comment]
This seems to be fixed as of version 1.0.0 on Curseforge. Thanks for your help!
